### ISSUE TITLE
Action showing error

### ISSUE THREAD

**Issue by Nef10** [BetaHuhn/repo-file-sync-action#106]
**🐞 Describe the bug**

The actions shows errors: `core.notice is not a function` and `syncTypeError: core.notice is not a function`, assignee and labels are not set. See [here](https://github.com/Nef10/sync-test/actions/runs/1207482124).

**📚 To Reproduce**

Run the action with a file to sync.

**💡 Expected behavior**

No error, assignee are labels set as configured.

**🖼️ Screenshots**

<img width="384" alt="Screen Shot 2021-09-06 at 5 14 39 PM" src="https://user-images.githubusercontent.com/4551135/132267214-534eeb75-9cbb-429b-9137-7f7fddbf3ea8.png">

**⚙️ Environment**

Latest

**📋 Additional context**

The problem was caused because the built after merging #101 was not done correctly (it used outdated dependencies). As I noted in the PR:

> When working on this I noticed that the current version does not seem to be built correctly. When I check out develop and run a build there is a diff to the checked in dist file. This change seems to be the bump of @actions/core to 1.5.0. This version is required for this change, so please make sure to update the dependencies to the version of the lock file before building.

**Comment by BetaHuhn** [comment]
Let me know if it works now.

**Comment by BetaHuhn** [comment]
Should be fixed.

Closing this for now, just reopen it if it still shows an error.

**Comment by Nef10** [comment]
Thank you!
