### ISSUE TITLE
sync a folder with deleteOrphaned fail to really delete files

### ISSUE THREAD

**Issue by thomasLeclaire** [BetaHuhn/repo-file-sync-action#113]
**🐞 Describe the bug**

I have a folder synchronized from the origin repo to the destination one with the deleteOrphaned setting enabled. 
If some files are added in this folder in the destination repo (or already exist before first sync) they are not deleted. 
In the same idea, if we delete the folder from the origin repo, we have no way to delete folder in the destination repo. 

got these errors in logs : 
```
Error: Cannot read property 'includes' of undefined
Error: TypeError: Cannot read property 'includes' of undefined
```

**💡 Expected behavior**

Some way to really sync folder between repos. ie delete all existing files if not in the root folder, and some way to delete a folder. 

**⚙️ Environment**
- Action version:  v1

**Comment by thomasLeclaire** [comment]
got a look on the code and in fact it's regression which was created due to this https://github.com/BetaHuhn/repo-file-sync-action/issues/97

if we don't have any exclude setting, the sync fail. Need to init the exclude setting to some default into code. 

On a side note,  I don't use a lot the github actions but even if there is explicit error, the github action is green, sounds abnormal to me.

**Comment by BetaHuhn** [comment]
Hey, thanks for taking the time to open this issue!

Will take a look at your PR for the fix and merge it asap.

Regarding the action not failing, see [#95](https://github.com/BetaHuhn/repo-file-sync-action/discussions/95)

**Comment by BetaHuhn** [comment]
The other part of your issue seems more like a feature request as it is not currently possible to delete a target folder when the source folder is deleted.

I will close this issue for now, please create a new [discussion](https://github.com/BetaHuhn/repo-file-sync-action/discussions/new?category=ideas) for the feature.
