### ISSUE TITLE
Replace & deleteOrphaned always have the value of default

### ISSUE THREAD

**Issue by barrydobson** [BetaHuhn/repo-file-sync-action#165]
**🐞 Describe the bug**

When setting a file to `replace: false` the setting is always `true`

**📚 To Reproduce**

Add a sync config that has the `replace` field set to `false` for a file

**💡 Expected behavior**

Expect file to not be replaced

**⚙️ Environment**
- Action version: latest

**Comment by BetaHuhn** [comment]
Thanks again @barrydobson!

This issue is resolved in version [v1.17.3](https://github.com/BetaHuhn/repo-file-sync-action/releases/tag/v1.17.3).
