### ISSUE TITLE
Actions fail in v1.17.18

### ISSUE THREAD

**Issue by svg153** [BetaHuhn/repo-file-sync-action#219]
**🐞 Describe the bug**

After this [merge](https://github.com/BetaHuhn/repo-file-sync-action/commit/9fc51b8c7e1a15d148ccd8b0ed0aa6a3df721010), our workflows failed.
Look at the screenshots.

**📚 To Reproduce**

- Having a working configuration
- Update the action version to v1.17.18
- Run the sync workflow

**💡 Expected behavior**

Works like version v1.17.17

**🖼️ Screenshots**

<details>
<summary>Action trace screenshot</summary>

![failed](https://user-images.githubusercontent.com/9192031/172156859-696a106d-5fba-4231-8f08-e8309a6c595f.png)

</details>

<details>
<summary>As seen in the commit screenshot.</summary>

![commit](https://user-images.githubusercontent.com/9192031/172156861-574a20ff-7f09-42b7-9a87-22b4b8d8b5c1.png)

</details>

- We made a change in PR-110. We added the variable `BRANCH_PREFIX: 'admin/sync/actions'` for the `Sync common GitHub Actions` workflow, but as you can see, all of them failed, not just the modified workflow.
- We made a PR-111 to put the version v1.17.17 and everything worked fine.

**⚙️ Environment**

- We use master, but it failed with [today's merge](https://github.com/BetaHuhn/repo-file-sync-action/commit/9fc51b8c7e1a15d148ccd8b0ed0aa6a3df721010), version [v1.17.18](https://github.com/BetaHuhn/repo-file-sync-action/releases/tag/v1.17.18)

**📋 Additional context**

- After the rollback to version v1.17.17 everything worked fine.
- cc: @gomete

**Comment by etremblay** [comment]
We have the same issue

**Comment by svg153** [comment]
It works again with the master version

Thanks :)

PD: For us, this issue would be closed
