### ISSUE TITLE
Exclude no longer works on version v1.18.00

### ISSUE THREAD

**Issue by rgeerkens** [BetaHuhn/repo-file-sync-action#276]
### 🐞 Describe the bug

When syncing folders between two repos suddenly the exclude functionality no longer works.

My code:
- source : ais/groeps
    dest : docs/ais
  - source : ais
    dest : ais
    exclude: |
      groeps
      docs

When syncing the source ais folder to destination folder ais the groeps and docs subfolders are also synced and should be ignored.

This worked perfectly prio to 18/11/2022 around 11:41AM GMT+1 ?

### 📚 To reproduce

Removing the code below stops syncing the mentioned subfolders : 

- source : ais
    dest : ais
    exclude: |
      groeps
      docs

When I re-aply the code, the groeps and docs folders are synced again (exclude is ignored).

### 💡 Expected behavior

The groeps and docs folders should not be synced as they are defined in the exclude list.

### ⚙️ Environment

Current runner version: '2.299.1'

**Comment by rgeerkens** [comment]
Everything works fine when forcing version 1.17.22 (so the issue must have been introduced with the latest version).

**Comment by boudewijn-zicht** [comment]
I'm having an issue with this as well, would love a fix for this usefull tool!

**Comment by kvmware** [comment]
Also, seeing this behavior.

**Comment by BetaHuhn** [comment]
Does the issue still come up on the latest version?

**Comment by boudewijn-zicht** [comment]
> Does the issue still come up on the latest version?

I can confirm that this issue is solved in the latest version, thanks @BetaHuhn!

**Comment by phnx47** [comment]
Checked, everything works!

**Comment by kvmware** [comment]
Thans @BetaHuhn !

**Comment by Abirdcfly** [comment]
Checked, this issue is fixed in latest version, Thanks @BetaHuhn \~\(≧▽≦)\~
