### ISSUE TITLE
Keep creating empty PRs after each push

### ISSUE THREAD

**Issue by mustafaozhan** [BetaHuhn/repo-file-sync-action#329]
### 🐞 Describe the bug

Hello,

I really loved the idea and integrated my project into `repo-file-sync-action`. Just realized that I am having empty PRs with 2 comits but no change. For example, the PR here: https://github.com/SubMob/LogMob/pull/115

How to avoid creating PRs if nothing changed ? 

I thought if I merge one of the empty PR then it will no longer create (since the 2 commits would be merged) but no luck, I actually merged one of these PRs, but new ones are keep coming. For example in the same repo I had this PR: https://github.com/SubMob/LogMob/pull/113 and merged it, but it didn't fix the situation.

### 📚 To reproduce

Not sure how you can reproduce this, but I put an example of the PRs, maybe you can see the logs, and I am willing to do anything you might think helpful

### 💡 Expected behavior

If there is no diff, no PR should be created.

### ⚙️ Environment

1.21.0, latest

**Comment by xgt001** [comment]
@mustafaozhan hi what was the fix here? I am facing the same issue. thank you so much!

**Comment by mustafaozhan** [comment]
Hey @xgt001 just seeing this now..

If you have a repo that you have both reference and the sync result then you need to have 2 files, one to be updated the other one needs to be not replaced but rather will trigger the sync only.

in my repo i had 2 renovate files and i add one into `relative` folder, here i save the `repo-file-sync-action` setup.

- relative/renovate.json (this one is where `repo-file-sync-action`  reads from) 
- renovate.json (this one is getting updated once `relative/renovate.json` is updated)

Hope I could explain.
